import { BasicLayout } from './basicLayout/BasicLayout';
import './global.scss'

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body><BasicLayout>{children}</BasicLayout></body>
    </html>
  );
}
